-d C:\Users\Dems1\Documents\Workspaces\Tang\Projects\ASCIItoMorse\impl\gwsynthesis\ASCIItoMorse.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst C:\Users\Dems1\Documents\Workspaces\Tang\Projects\ASCIItoMorse\src\ASCIItoMorse.cst
-cfg C:\Users\Dems1\Documents\Workspaces\Tang\Projects\ASCIItoMorse\impl\pnr\device.cfg
-sdc C:\Users\Dems1\Documents\Workspaces\Tang\Projects\ASCIItoMorse\src\ASCIItoMorse.sdc
-bit
-tr
-ph
-warning_all
-timing
-cst_error
